title: Knot Data
email: ryan.j.maguire.gr@dartmouth.edu
description: Tables of knot invariants.
baseurl: "/"
url: "https://knots.dartmouth.edu"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
